= BDR Gateway Test Client

This is a small Python program made to test the http://bdrgateway.surroundaustralia.com[BDR Gateway] API which is used to absorb data into the _Biodiversity Data Repository_ being built for the https://www.awe.gov.au[Department of Agriculture, Water and the Environment].

This tool synthesis data that emulates the kind of messages likley to be sent to the BDR. The messages conform to the https://surroundaustralia.github.io/abis/specification.html[ABIS Specification] although we also expect to test messages that deliberately don't conform. The majority of the messages' content conforms to the https://linkeddata.tern.org.au/information-models/tern-ontology[TERN Ontology] so it mainly consists of `Sampling`, `Sample`, `Site`, `Observation` and `Dataset` objects.

== Data

=== Data element coverage



=== Example Messages

See folder `tests_data/messages/`. These are the same message examples listed in the BDR Gateway.

=== Validators

See folder `tests_data/validators/`.

Currently only:

* BDR Messages Validator
* VocPub BDR Validator

TERN validator to be added soon

== Use

* `validate_egs.py` - attempts to validate each example message file using all the validators combined
* `validate_egs_rdf.py` - just checks each example is valid RDF
** useful if new problematic example files need testing as at least syntactically before full use in validation tests
* `create_sampling.py` - creates instances of Sampling and Sample from data (Python dict) and packages it within a BDR `CreateMessage`
* 'utils.py' - This page includes a create_dataset function which allows creation of sampling data. The function can create up to 10000 datapoints and serializes the data to the 'test.ttl' file.
** This function can be used by altering the create_dataset code to something like create_dataset(2) -> where it creates 2 sampling data points and associated features of interest and datasets.
